### PR TITLE
Fix for BMC-446: Add an order column for scheduled assessments

### PR DESCRIPTION
**Pull request by nategbrown9**
- [x] Still need to update iOS binaries

This is a schema change to the schedule cache so need to verify migration:
- [x] iOS - Test reproing bug on broken build then updating to fixed build
- [x] android - Test reproing bug on broken build then updating to fixed build

### CODE REVIEW

**Review by Erin-Mounts — APPROVED** [review]
looks good to me

**Comment by syoung-smallwisdom** [comment]
So this doesn't migrate and will crash an upgrade from build 94 on iOS.

**Comment by syoung-smallwisdom** [comment]
Confirmed that migrating the views works and migration now succeeds. Thanks!

**Review by syoung-smallwisdom — APPROVED** [review]
Looks good. 

Need to figure out what's up with the tests. Tagged as 0.15.2 so it will link on iOS but not Android.

**Pull request merged**
